### ISSUE TITLE
Roadmap for v3 ( Reanimated v2 )

### ISSUE THREAD

**Issue by gorhom** [gorhom/react-native-bottom-sheet#76]
### Bottom Sheet v3 ( Reanimated v2 )

These are the planned improvements and features for v3.

#### Improvements
- [x] Change the current v2 alpha release into v3.
- [x] Fix measuring bottom sheet container to use its actual size than window height.
- [x] Add documentation site.

#### Features
- [x] Add `BottomSheetModal` 🔥
- [x] Add `animateOnMount` prop to snap to the initial snap point index when the sheet is mounted.
- [x] Add `onAnimate` callback
- [x] Add dynamic snap points feature. 
- [x] Add `enablePanningGesture` prop to enable panning gesture of the sheet.
- [x] Add `enableContentPanningGesture` prop to allow panning sheet by its content view or scrollables.
- [x] Allow scrollables bouncing.
- [x] Add default backdrop #45.

## Install Stable Release

```ts
yarn add @gorhom/bottom-sheet@3.0.0
```

also check out the [new documents website](https://gorhom.github.io/react-native-bottom-sheet/) 🎉

**Comment by likern** [comment]
I have found in `package.json` that `0.62.2` version is used for development

```ts
"devDependencies": {
    "react-native": "^0.62.2"
  },
```
while  in `peerDependencies` any version is allowed
```ts
"peerDependencies": {
    "react-native": "*"
  },
```
I think it's not possible to support any version because inherently package depends on `0.62.2`.
Maybe these version should be synced?

Having matrix and strategy of which versions of React Native are supported, when getting deprecated and unsupported can be valuable.

**Comment by izakfilmalter** [comment]
Would be great to get `useBottomSheetModal` supported with Reanimated v2.

**Comment by AppKidd** [comment]
How many coffees ☕ for bounce & spring animation support?

**Comment by likern** [comment]
> How many coffees ☕ for bounce & spring animation support?

Could you describe interface, how you envision it?
This should be fairly simple.

I have my own https://github.com/breeffy/react-native-bottom-sheet, fork of this one. Targeting specifically Reanimated V2. No ETA, but might consider adding this feature.

**Comment by AppKidd** [comment]
@likern I'm looking to achieve the closest possible to a completely native feel. If you compare to the likes of Maps or Find My on iOS there are a couple of things that stick out: a spring style animation when swiping the view and also bouncing when you reach the bottom of the view.

**Comment by gorhom** [comment]
@Appkidd currently am working now copy features from v2 to v3, bouncing feature will be added with or after the v3 release 👍

**Comment by AppKidd** [comment]
@gorhom Excellent! Will send some coffee your way shortly

**Comment by gorhom** [comment]
i just released v3 🎉

```bash
yarn add @gorhom/bottom-sheet@3.0.0
```

**Comment by theodelebarre** [comment]
@gorhom It would be great to be able to use the v3 with expo, sadly the reanimated version you're using isn't compatible. Do you think it's possible to at least add enableContentPanningGesture to the v2 ?

Very nice job anyway for that package. Thanks a lot!

**Comment by gorhom** [comment]
hi @theodelebarre ,`enableContentPanningGesture` is already available on v2, also what version of expo are you using ?

**Comment by theodelebarre** [comment]
I'm on Expo 40, 
installing the v2.0.0 as well as expo add reanimated, gesture handler -> the app crashes instantly;

Right now I've got this version installed -> "@gorhom/bottom-sheet": "^1.4.1"

**Comment by gorhom** [comment]
@theodelebarre i tested `BottomSheet v2` with expo 40, and it works fine 

https://expo.io/@gorhom/projects/bottom-sheet-v2

**Comment by gudberg** [comment]
@gorhom, is v3 more suited for implementing pull-to-refresh with Flatlist/Sectionlist? What would be the best way to refresh the list inside the BottomSheet?

Thanks for the library!

**Comment by gorhom** [comment]
@gudberg it is something complicated , because if you allow `pull-to-refresh` that means you no longer be able to pan down the sheet by the scrollable `FlatList`, `ScrollView` or `SectionList`

**Comment by mr-moto** [comment]
Hey @gorhom, 
Quick question
Im trying to use an external library ( specifically `react-native-elements` `CheckBox` component ) within the bottom sheet and they obviously wont work properly since they use regular RN Touchables.
What would be the correct way to use libraries within `BottomSheetModal` that use the regular RN Touchables?

EDIT: `react-native-elements` components have a prop to pass in a touchable component which resolves the above. But what if there are 3rd party libraries that don't allow passing touchable components?

**Comment by gorhom** [comment]
@mr-moto i am working on a workaround that will allow all touchables to be working ONLY when the sheet expanded, will submit a pr soon 👍
